name: zorrr_black_ai
description: "Zorrr Black AI OS"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: any

flutter:
  uses-material-design: true
